import type { Board } from "../tetris/Board";
import type { ActivePiece } from "../tetris/ActivePiece";
import type { TetrominoType } from "../tetris/Cell";
import type { HoldSlot } from "../tetris/HoldSlot";
import type { CombatResult } from "./CombatResult";
import type { RelicInventory } from "../relic/RelicInventory";
import type { EnemyDefinition } from "../enemy/EnemyDefinition";
import type { EnemyIntent } from "../enemy/EnemyIntent";
import type { GameEvent } from "../shared/GameEvent";
import type { LastSpinAction, SpinResult } from "../tetris/SpinDetector";
import type { GarbageQueue } from "./GarbageQueue";
import type { ClearResult } from "../tetris/ClearResult";
import type { ComboB2BResult } from "./ComboB2BTracker";
import type { CombatFeedbackEvent } from "./CombatFeedbackEvent";
import type { EnemyCalculatedStats } from "../balance/balanceTypes";
import type { TetrisRuleSet } from "../tetris/TetrisRuleSet";
import type { BattleResultSummary, CombatTelemetry } from "./BattleResultSummary";

export type PlayerCombatState = {
  hp: number;
  board: Board;
  activePiece?: ActivePiece;
  pieceQueue: TetrominoType[];
  nextPieces: TetrominoType[];
  holdSlot: HoldSlot;
  hold?: TetrominoType;
  holdSlots: TetrominoType[];
  maxHoldSlots: number;
  hasHeldThisPiece: boolean;
  holdUsedThisBattle: boolean;
  relicInventory: RelicInventory;
  combo: number;
  comboDisplayCount: number;
  backToBackActive: boolean;
  backToBackCount: number;
  fastChainCount: number;
  isFastState: boolean;
  lastPieceLockTimeMs?: number;
  actionCount: number;
  gravityElapsedMs: number;
  lockElapsedMs: number;
  softDropActive: boolean;
  isGrounded: boolean;
  groundedSinceMs?: number;
  lockResetCount: number;
  lastLockResetAtMs?: number;
  lockResetLimitReachedLogged: boolean;
  lastSpinAction?: LastSpinAction;
};

export type EnemyCombatState = {
  definition: EnemyDefinition;
  hp: number;
  maxHp: number;
  calculatedStats?: EnemyCalculatedStats;
  currentIntent?: EnemyIntent;
  pendingGarbage: number;
  garbageQueue: GarbageQueue;
};

export type CombatState = {
  player: PlayerCombatState;
  enemy: EnemyCombatState;
  ruleSet: TetrisRuleSet;
  ruleSetModifierDebug?: {
    baseRuleSet: TetrisRuleSet;
    effectiveRuleSet: TetrisRuleSet;
    appliedRuleRelicIds: string[];
  };
  telemetry?: CombatTelemetry;
  result: CombatResult;
  lastAttack?: number;
  lastBaseAttack?: number;
  lastLinesCleared?: number;
  lastSpinResult?: SpinResult;
  lastClearResult?: ClearResult;
  lastComboB2BResult?: ComboB2BResult;
  lastFeedbackEvent?: CombatFeedbackEvent;
  lastBattleResultSummary?: BattleResultSummary;
  log: GameEvent[];
};
