export type FieldAnalysisConfig = {
  visibleHeight: number;
  boardWidth: number;
  lowStackMaxHeight: number;
  midStackMaxHeight: number;
  highStackThreshold: number;
  criticalStackThreshold: number;
  fewHolesMax: number;
  manyHolesThreshold: number;
  criticalHolesThreshold: number;
  garbagePressureWarningRows: number;
  garbagePressureDangerRows: number;
  garbagePressureCriticalRows: number;
  cleanFieldMaxHeight: number;
  cleanFieldMaxHoles: number;
  cleanFieldMaxBumpiness: number;
  cleanFieldMaxGarbageRows: number;
  cleanFieldRequiresNoCriticalStack: boolean;
  stableFieldMaxHeight: number;
  stableFieldMaxHoles: number;
  stableFieldMaxBumpiness: number;
  stableFieldMaxGarbageRows: number;
  stableFieldMinScore: number;
  wellMinDepth: number;
  deepWellThreshold: number;
  veryDeepWellThreshold: number;
  allowEdgeWell: boolean;
  warningHeightThreshold: number;
  dangerHeightThreshold: number;
  criticalHeightThreshold: number;
  warningHoleThreshold: number;
  dangerHoleThreshold: number;
  criticalHoleThreshold: number;
  warningGarbageRows: number;
  dangerGarbageRows: number;
  criticalGarbageRows: number;
  dangerScoreWarning: number;
  dangerScoreDanger: number;
  dangerScoreCritical: number;
  dangerHeightScoreWeight: number;
  dangerHoleScoreWeight: number;
  dangerGarbageScoreWeight: number;
  dangerBumpinessScoreWeight: number;
  criticalBumpinessThreshold: number;
};

export const defaultFieldAnalysisConfig: FieldAnalysisConfig = {
  visibleHeight: 20,
  boardWidth: 10,
  lowStackMaxHeight: 9,
  midStackMaxHeight: 14,
  highStackThreshold: 15,
  criticalStackThreshold: 18,
  fewHolesMax: 2,
  manyHolesThreshold: 6,
  criticalHolesThreshold: 10,
  garbagePressureWarningRows: 4,
  garbagePressureDangerRows: 8,
  garbagePressureCriticalRows: 12,
  cleanFieldMaxHeight: 10,
  cleanFieldMaxHoles: 1,
  cleanFieldMaxBumpiness: 8,
  cleanFieldMaxGarbageRows: 2,
  cleanFieldRequiresNoCriticalStack: true,
  stableFieldMaxHeight: 6,
  stableFieldMaxHoles: 0,
  stableFieldMaxBumpiness: 4,
  stableFieldMaxGarbageRows: 0,
  stableFieldMinScore: 100,
  wellMinDepth: 2,
  deepWellThreshold: 4,
  veryDeepWellThreshold: 6,
  allowEdgeWell: true,
  warningHeightThreshold: 10,
  dangerHeightThreshold: 15,
  criticalHeightThreshold: 18,
  warningHoleThreshold: 3,
  dangerHoleThreshold: 6,
  criticalHoleThreshold: 10,
  warningGarbageRows: 4,
  dangerGarbageRows: 8,
  criticalGarbageRows: 12,
  dangerScoreWarning: 30,
  dangerScoreDanger: 60,
  dangerScoreCritical: 85,
  dangerHeightScoreWeight: 40,
  dangerHoleScoreWeight: 30,
  dangerGarbageScoreWeight: 20,
  dangerBumpinessScoreWeight: 10,
  criticalBumpinessThreshold: 16,
};
