import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { balanceConfig } from "../src/data/balanceConfig";
import { difficultyDefinitions } from "../src/data/difficultyDefinitions";
import { generateBalancePreview, type BalancePreviewRow } from "../src/debug/balanceDebug";
import type { DifficultyId } from "../src/domain/balance/balanceTypes";

const difficultyOrder: DifficultyId[] = ["explorer", "standard", "advanced", "master", "void"];
declare const process: { cwd: () => string };

const outputPath = resolve(process.cwd(), "reports/balance-1-30-by-difficulty.txt");

const lines: string[] = [
  "TetroLogue Balance Report",
  "Generated: 2026-05-25",
  "",
  "Scope: floors 1-30, all difficulties",
  "Notes:",
  "- Enemy selection uses the deterministic balance preview seed from src/debug/balanceDebug.ts.",
  "- Values are generated by the live balance calculators, not duplicated formulas.",
  "- DifficultyRatio columns compare enemyDemand against rough B/A/S player throughput anchors.",
  "",
  "Config Snapshot",
  `maxFloor=${balanceConfig.floorScaling.maxFloor}`,
  `hpScale=${balanceConfig.hp.hpScale}`,
  `baseGravityMs=${balanceConfig.gravity.baseGravityMs}`,
  `minGravityMs=${balanceConfig.gravity.minGravityMs}`,
  `defaultGarbageDelayActions=${balanceConfig.garbage.defaultGarbageDelayActions}`,
  "",
];

for (const difficultyId of difficultyOrder) {
  const difficulty = difficultyDefinitions[difficultyId];
  const rows = generateBalancePreview(difficultyId).rows;
  const bossRows = rows.filter((row) => row.role === "boss" || row.role === "miniboss" || row.role === "finalBoss");

  lines.push("=".repeat(140));
  lines.push(`${difficulty.name} (${difficulty.id})`);
  lines.push(difficulty.description);
  lines.push(
    `multipliers: demand=${difficulty.demandMultiplier}, hp=${difficulty.hpMultiplier}, gravity=${difficulty.gravityMultiplier}, garbage=${difficulty.garbageMultiplier}, pattern=${difficulty.patternMultiplier}`,
  );
  lines.push("");
  lines.push("Boss / Miniboss / Final Boss Summary");
  lines.push(formatRows(bossRows));
  lines.push("");
  lines.push("All Floors");
  lines.push(formatRows(rows));
  lines.push("");
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, lines.join("\n"), "utf8");

console.log(`Balance report written: ${outputPath}`);

function formatRows(rows: BalancePreviewRow[]): string {
  const headers: (keyof BalancePreviewRow)[] = [
    "floor",
    "difficulty",
    "selectedEnemyId",
    "selectedEnemyName",
    "role",
    "traits",
    "baseDemand",
    "enemyDemand",
    "enemyDemandToBaseRatio",
    "maxHp",
    "hpToBaseHpRatio",
    "gravityMs",
    "enemyGpm",
    "cappedGpm",
    "uncappedEnemyGpm",
    "intentEveryActions",
    "garbageLines",
    "targetTime",
    "difficultyRatioB",
    "difficultyRatioA",
    "difficultyRatioS",
    "ratioBAvgRelic",
    "ratioAAvgRelic",
    "ratioSAvgRelic",
  ];
  const widths = headers.map((header) =>
    Math.max(
      String(header).length,
      ...rows.map((row) => formatCell(row[header]).length),
    ),
  );
  const headerLine = headers.map((header, index) => pad(String(header), widths[index])).join(" | ");
  const dividerLine = widths.map((width) => "-".repeat(width)).join("-+-");
  const rowLines = rows.map((row) =>
    headers.map((header, index) => pad(formatCell(row[header]), widths[index])).join(" | "),
  );
  return [headerLine, dividerLine, ...rowLines].join("\n");
}

function formatCell(value: BalancePreviewRow[keyof BalancePreviewRow]): string {
  return String(value ?? "");
}

function pad(value: string, width: number): string {
  return value.padEnd(width, " ");
}
